jobs:
  gradle:
    name: Gradle CI Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - continue-on-error: true
      name: Prepare Java 11
      uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: 11
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/*.gradle.kts')
          }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Build project
      run: './gradlew :app:assembleCI

        '
name: PR Build CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
