jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v4
      with:
        any-of-labels: bug
        close-issue-message: This issue was closed because it has been stalled for
          5 days with no activity.
        days-before-close: 5
        days-before-stale: 30
        exempt-issue-labels: Confirmed
        stale-issue-label: no-issue-activity
        stale-issue-message: This issue is stale because it has been open 30 days
          with no activity. Remove stale label or comment or this will be closed in
          5 days.
    - continue-on-error: true
      uses: actions/stale@v4
      with:
        close-issue-message: This issue was closed because it has been stalled for
          30 days with no activity.
        days-before-close: 30
        days-before-stale: 90
        only-issue-labels: bug,Confirmed
        stale-issue-label: no-issue-activity
        stale-issue-message: This issue is stale because it has been confirmed as
          a bug but still been opened 90 days with no activity. Remove stale label
          or comment or this will be closed in 30 days.
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
